[build]
# Build phase - no database connection available
cmd = ["pnpm", "install", "--frozen-lockfile", "&&", "pnpm", "run", "build"]

[start]
# Start phase - database connection available
cmd = ["pnpm", "run", "railway:start"]

[variables]
# Ensure Node.js environment
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.build]
# Install dependencies and build (no DB connection)
cmds = [
  "pnpm install --frozen-lockfile",
  "prisma generate",
  "nest build"
]

[phases.start]
# Runtime phase (DB connection available)
cmd = "pnpm run railway:start"

# Use pnpm instead of npm
[providers]
nodejs = "18"

[nixpkgs]
# Required system packages
pkgs = ["nodejs_18", "pnpm"]
